---
variables:
  DOCKERHUB_REPO_NAME: csp
  ENABLE_ARM64: 'true'
  ENABLE_ARMv7: 'true'
  ENABLE_ARMv6: 'true'
  ENABLE_386: 'true'

include:
  - project: 'ix.ai/ci-templates'
    file: '/python-project.yml'
