---
variables:
  DOCKERHUB_REPO_NAME: csp
  GITHUB_REPO_NAME: ix-ai/csp
  ENABLE_AMD64: 'true'
  ENABLE_ARM64: 'true'
  ENABLE_ARMv7: 'true'
  ENABLE_ARMv6: 'true'
  ENABLE_386: 'true'

include:
  - project: 'egos-tech/pipelines'
    file: '/python-project.yml'
  - template: Security/SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml

sast:
  stage: test
